# АРХИТЕКТУРА КАК КОД
:toc:

## 1. Подходы к созданию документаци

### 1.1. WYSIWYG (what you see is what you get)

[quote]
----
Интерфейс, который позволяет редактировать контент так,
чтобы он в процессе работы выглядел практически так же,
как и конечный результат, документ или веб-страница.
----

#### 1.1.1. Преимущества подхода

* Низкий порог вхождения в технологии,
так как сразу виден конечный результат
(интуитивно понятный интерфейс редакторов).

#### 1.1.2. Недостатки подхода

* Требуются дорогостоящие сервера для обеспечения
совместной работы над документацией.

* Низкая производительность при работе
с большим объемом текста и графических изображений.

* Отсутствует возможность работать офлайн.

* Отсутствуют исходники графических изображений.

* Отсутствует возможность экспортировать и
импортировать документацию между проектами и окружениями.

### 1.2. DOC AS CODE (документация как код)

[qoute]
----
Подход к разработке технической документации,
который подразумевает хранение требований и
архитектурных решений в виде текстовых файлов.
----

#### 1.2.1. Преимущества подхода

* Возможность разрабатывать большие по объему тексты без снижения производительности при публикации материалов.

* Возможно по отдельности работать над содержанием и оформлением документации.

* Возможность разрабатывать графические изображения в виде программного кода с последующей загрузкой в Confluence.

* Возможность отслеживать историю изменений документов и локально вести разработку без подключения к сети интернет.

* Возможность автоматизации генерации документации для снижения количества рутинной работы и ошибок в создаваемой документации.

#### 1.2.2. Недостатки подхода

* Высокий порог вхождения в стек технологий для технических специалистов с погружением в разработку программного кода.

* Наличие неявных ограничений технологий при создании текстового описания и графических изображений.



