# АРХИТЕКТУРА КАК КОД
:toc:
:toc-title: Содержание

## Цели доклада

1. Обзор подхода "Документация как код"

2. Обзор инструментов проектирования и документирования баз данных

3. Обзор инструментов проектирования и документирования rest api

## 1. Подходы к созданию документаци

### 1.1. WYSIWYG (what you see is what you get)

[quote]
----
Интерфейс, который позволяет редактировать контент так,
чтобы он в процессе работы выглядел практически так же,
как и конечный результат, документ или веб-страница.
----

#### 1.1.1. Преимущества подхода

* Низкий порог вхождения в технологии,
так как сразу виден конечный результат
(интуитивно понятный интерфейс редакторов).

#### 1.1.2. Недостатки подхода

* Требуются дорогостоящие сервера для обеспечения
совместной работы над документацией.

* Низкая производительность при работе
с большим объемом текста и графических изображений.

* Отсутствует возможность работать офлайн.

* Отсутствуют исходники графических изображений.

* Отсутствует возможность экспортировать и
импортировать документацию между проектами и окружениями.

### 1.2. DOC AS CODE (документация как код)

[qoute]
----
Подход к разработке технической документации,
который подразумевает хранение требований и
архитектурных решений в виде текстовых файлов.
----

#### 1.2.1. Преимущества подхода

* Возможность разрабатывать большие по объему тексты без снижения производительности при публикации материалов.

* Возможно по отдельности работать над содержанием и оформлением документации.

* Возможность разрабатывать графические изображения в виде программного кода с последующей загрузкой в Confluence.

* Возможность отслеживать историю изменений документов и локально вести разработку без подключения к сети интернет.

* Возможность автоматизации генерации документации для снижения количества рутинной работы и ошибок в создаваемой документации.

#### 1.2.2. Недостатки подхода

* Высокий порог вхождения в стек технологий для технических специалистов с погружением в разработку программного кода.

* Наличие неявных ограничений технологий при создании текстового описания и графических изображений.

## 2. Языки разметки

### 2.1. Верстка текста

* HTML

* Wiki

* MarkDown

* Asciidoc

* Tex

### 2.2. Верстка изображений

* Plantuml

* GraphViz

## 3. Используемый стек технологий

[cols="0,100"]
|===

|01.
|Git

|02.
|Java 21

|03.
|Apache Maven 3

|04.
|Plantuml

|05.
|https://www.jetbrains.com/idea/download/[IntelliJ IDEA (Community)]

|06.
|Plantuml Plugin (IntelliJ IDEA)

|07.
|Asciidoc Plugin (IntelliJ IDEA)

|08.
|Diagram.net Plugin (IntelliJ IDEA)

|09.
|Asciidoc

|10.
|asciidoctor-maven-plugin

|11.
|Confluence

|12.
|confluence-maven-plugin

|13.
|https://www.liquibase.com[Liquibase]

|14.
|liquibase-maven-plugin

|15.
|OpenAPI

|16.
|openapi-maven-plugin

|17.
|Apicurio

|18.
|apicurio-maven-plugin

|===

## 4. Организация рабочего пространства

### 4.1. Минимальная структура проекта

*Структура проекта*

----
/data/my-project/.git # Папка git-репозитория
/data/my-project/pom.xml # Проект Apache Maven
/data/my-project/src/main/asciidoc/index.adoc # Документ Asciidoc
----

*Файл "pom.xml"*

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.volnenko.doc</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>2.2.6</version>
                <executions>
                    <execution>
                        <id>convert-to-html</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
----

*Файл "index.adoc"*

----
# Hello World!
----

### 4.2. Настройка публикации в Confluence

*Структура проекта*

----
/data/my-project/.git # Папка git-репозитория
/data/my-project/pom.xml # Проект Apache Maven
/data/my-project/src/main/asciidoc/index.adoc # Документ Asciidoc
----

*Файл "pom.xml"*

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.volnenko.doc</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>2.2.6</version>
                <executions>
                    <execution>
                        <id>convert-to-html</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
----

### 4.3. Настройка генерации документации базы данных по мета-модели Liquibase

### 4.4. Настройка генерации документации rest api по мета-модели OpenAPI