# АРХИТЕКТУРА КАК КОД
:toc:
:toc-title: Содержание

## Цели доклада

1. Обзор подхода "Документация как код".

2. Обзор инструментов проектирования и документирования баз данных.

3. Обзор инструментов проектирования и документирования rest api.

4. Создание рабочей группы в рамках подхода "Архитектура как код".

## 1. Подходы к созданию документаци

### 1.1. WYSIWYG (what you see is what you get)

[quote]
----
Интерфейс, который позволяет редактировать контент так,
чтобы он в процессе работы выглядел практически так же,
как и конечный результат, документ или веб-страница.
----

#### 1.1.1. Преимущества подхода

* Низкий порог вхождения в технологии,
так как сразу виден конечный результат
(интуитивно понятный интерфейс редакторов).

#### 1.1.2. Недостатки подхода

* Требуются дорогостоящие сервера для обеспечения
совместной работы над документацией.

* Низкая производительность при работе
с большим объемом текста и графических изображений.

* Отсутствует возможность работать офлайн.

* Отсутствуют исходники графических изображений.

* Отсутствует возможность экспортировать и
импортировать документацию между проектами и окружениями.

### 1.2. DOC AS CODE (документация как код)

[qoute]
----
Подход к разработке технической документации,
который подразумевает хранение требований и
архитектурных решений в виде текстовых файлов.
----

#### 1.2.1. Преимущества подхода

* Возможность разрабатывать большие по объему тексты без снижения производительности при публикации материалов.

* Возможно по отдельности работать над содержанием и оформлением документации.

* Возможность разрабатывать графические изображения в виде программного кода с последующей загрузкой в Confluence.

* Возможность отслеживать историю изменений документов и локально вести разработку без подключения к сети интернет.

* Возможность автоматизации генерации документации для снижения количества рутинной работы и ошибок в создаваемой документации.

* Все используемые инструменты для разработки документации полностью бесплатные.

#### 1.2.2. Недостатки подхода

* Высокий порог вхождения в стек технологий для технических специалистов с погружением в разработку программного кода.

* Наличие неявных ограничений технологий при создании текстового описания и графических изображений.

## 2. Языки разметки

### 2.1. Верстка текста

* HTML

* Wiki

* MarkDown

* *Asciidoc*

* Tex

### 2.2. Верстка изображений

* *Plantuml*

* GraphViz

## 3. Используемый стек технологий

[cols="0,100"]
|===

|01.
|Git

|02.
|Java 21

|03.
|Apache Maven 3

|04.
|Plantuml

|05.
|https://www.jetbrains.com/idea/download/[IntelliJ IDEA (Community)]

|06.
|Plantuml Plugin (IntelliJ IDEA)

|07.
|Asciidoc Plugin (IntelliJ IDEA)

|08.
|Diagram.net Plugin (IntelliJ IDEA)

|09.
|Asciidoc

|10.
|asciidoctor-maven-plugin

|11.
|Confluence

|12.
|confluence-maven-plugin

|13.
|https://www.liquibase.com[Liquibase]

|14.
|liquibase-maven-plugin

|15.
|OpenAPI

|16.
|openapi-maven-plugin

|17.
|Apicurio

|18.
|apicurio-maven-plugin

|===

## 4. Организация рабочего пространства

### 4.1. Минимальная структура проекта

*Структура проекта*

----
/data/my-project/.git # Папка git-репозитория
/data/my-project/pom.xml # Проект Apache Maven
/data/my-project/src/main/asciidoc/index.adoc # Документ Asciidoc
----

.*pom.xml*
[%collapsible]
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.volnenko.doc</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>2.2.6</version>
                <executions>
                    <execution>
                        <id>convert-to-html</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
----
====

.*index.adoc*
[%collapsible]
====
[source,asciidoc]
----
# Hello World!
----
====

### 4.2. Настройка публикации документации в Confluence

*Структура проекта*

----
/data/my-project/.git # Папка git-репозитория
/data/my-project/pom.xml # Проект Apache Maven
/data/my-project/src/main/asciidoc/index.adoc # Документ Asciidoc

/Users/username/.m2/settings.xml # Файл с настройками Apache Maven
----

.*pom.xml*
[%collapsible]
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.volnenko.doc</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>2.2.6</version>
                <executions>
                    <execution>
                        <id>convert-to-html</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
----
====

.*settings.xml*
[%collapsible]
====
[source,xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <servers>
        <server>
            <id>confluence</id>
            <username>test</username>
            <password>1234</password>
        </server>
    </servers>

</settings>
----
====

### 4.3. Настройка генерации документации базы данных

*Структура проекта*

----
/data/my-project/.git # Папка git-репозитория
/data/my-project/pom.xml # Проект Apache Maven
/data/my-project/src/main/asciidoc/archdoc.adoc # Документ Asciidoc
/data/my-project/src/main/resources/database/task.yaml # Описание таблицы "app_task"
/data/my-project/src/main/resources/database/project.yaml Описание таблицы "app_project"
/data/my-project/src/main/resources/database/status_type.yaml Описание перечисления "status_type"

/data/my-project/src/main/asciidoc/database.adoc # Сгенерированное описание базы данных
/data/my-project/src/main/asciidoc/erd_logic.puml # Сгенерированная логическая схема в Plantuml
/data/my-project/src/main/asciidoc/erd_logic.svg # Скомпилированная логическая схема в SVG
/data/my-project/src/main/asciidoc/erd_physic.puml # Сгенерированная физическая схема в Plantuml
/data/my-project/src/main/asciidoc/erd_physic.svg # Скомпилированная физическая схема в SVG
----

.*project.yaml*
[%collapsible]
====
[source,yaml]
----
---
databaseChangeLog:
  - changeSet:
      id: project
      author: denis.volnenko
      changes:
        - createTable:
            schemaName: public
            catalogName: tm
            tableName: app_project
            remarks: Проект
            columns:
              - column:
                  name: id
                  type: uuid
                  autoIncrement: true
                  remarks: Уникальный код
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: text
                  remarks: Название
                  defaultValue: ""
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: text
                  remarks: Описание
                  defaultValue: ""
                  constraints:
                    nullable: false
              - column:
                  name: status_type
                  type: text
                  remarks: Статус
                  defaultValue: "NOT_STARTED"
                  constraints:
                    nullable: false
              - column:
                  name: created
                  type: timestampz
                  remarks: Дата создания
                  constraints:
                    nullable: false
              - column:
                  name: updated
                  type: timestampz
                  remarks: Дата обновления
                  constraints:
                    nullable: false
----
====

.*task.yaml*
[%collapsible]
====
[source,yaml]
----
---
databaseChangeLog:
- changeSet:
    id: task
    author: denis.volnenko
    changes:
      - createTable:
          schemaName: public
          catalogName: tm
          tableName: app_task
          remarks: Задачи
          columns:
            - column:
                name: id
                type: uuid
                remarks: Уникальный код
                autoIncrement: true
                constraints:
                  primaryKey: true
                  nullable: false
            - column:
                name: name
                type: text
                remarks: Название
                defaultValue: ""
                constraints:
                  nullable: false
            - column:
                name: description
                type: text
                remarks: Описание
                defaultValue: ""
                constraints:
                  nullable: false
            - column:
                name: status_type
                type: text
                remarks: Статус
                defaultValue: "NOT_STARTED"
                constraints:
                  nullable: false
            - column:
                name: project_id
                type: uuid
                remarks: Код проекта
                constraints:
                  foreignKey:
                    referencedColumnNames: id
                    referencedTableName: app_project
                  nullable: false
            - column:
                name: created
                type: timestampz
                remarks: Дата создания
                constraints:
                  nullable: false
            - column:
                name: updated
                type: timestampz
                remarks: Дата обновления
                constraints:
                  nullable: false
----
====

.*status_type.yaml*
[%collapsible]
====
[source,yaml]
----
---
databaseChangeLog:
- changeSet:
    id: status_type
    author: denis.volnenko
    changes:
      - createType:
          schemaName: public
          catalogName: tm
          typeName: status_type
          remarks: Статус
          values:
            - value:
                name: NOT_STARTED
                remarks: Не начато
            - value:
                name: IN_PROGRESS
                remarks: В процессе
            - value:
                name: COMPLETE
                remarks: Завершено
----
====

.*archdoc.adoc*
[%collapsible]
====
[source,asciidoc]
----
 # АРХИТЕКТУРНЫЙ ДОКУМЕНТ
 :toc:
 :toc-title: Содержание

 include::database.adoc[]
----
====

### 4.4. Настройка генерации документации rest api

include::page-database.adoc[]

