@startuml 
left to right direction 
'!pragma graphviz_dot jdot 
!pragma layout smetana 
entity "Проект" as app_project {
    *"Уникальный код" : "Целочисленный"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

entity "Задачи" as app_task {
    *"Уникальный код" : "Целочисленный"
---
    "Название" : "Строка"
    "Описание" : "Строка"
    "Статус" : "Строка"
    "Код проекта" : "Целочисленный"
    "Дата создания" : "Дата/Время"
    "Дата обновления" : "Дата/Время"
}

"app_task" }--|| "app_project"

@enduml
